Parameters:
  ExecRole:
    Type: String
    Default: arn:aws:iam::971134353672:role/LabRole
  ProdTableName:
    Type: String
    Default: gas_production_cost

Resources:
  # Dynamo
  ProductionDynamoDB:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: !Ref ProdTableName
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

  # Lambdas
  ProductionFetcherFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Lambda_ProductionFetcher
      Handler: production_fetcher.lambda_handler
      Role: !Ref ExecRole
      Code:
        S3Bucket: !ImportValue Bucketforcodes
        S3Key: production_fetcher.zip
      Runtime: python3.12
      Timeout: 60
  ProductionUpdaterFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Lambda_ProductionUpdater
      Handler: production_updater.lambda_handler
      Role: !Ref ExecRole
      Code:
        S3Bucket: !ImportValue Bucketforcodes
        S3Key: production_updater.zip
      Runtime: python3.12
      Timeout: 60
  
  FetcherApiGWPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ProductionFetcherFunction.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
  UpdaterApiGWPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ProductionUpdaterFunction.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'

Outputs:
  ProductionFetcherArn:
    Description: "Production fetcher lambda ARN"
    Value: !GetAtt ProductionFetcherFunction.Arn
    Export:
      Name: ProductionFetcherArn
  ProductionUpdaterArn:
    Description: "Production updater lambda ARN"
    Value: !GetAtt ProductionUpdaterFunction.Arn
    Export:
      Name: ProductionUpdaterArn