Parameters:
  PublishStageName:
    Type: String
    Default: prod

Resources:
  UtilitiesApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: MyUtilitiesApi
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - PUT
          - POST
        AllowHeaders:
          - Authorization
          - Content-Type
          - X-Requested-With
  # ---- Integrations ----
  # Report Lambdas
  PublishLambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref UtilitiesApi
      Description: Publish Lambda API GW Integration
      IntegrationType: AWS_PROXY
      PayloadFormatVersion: "2.0"
      IntegrationUri: !Sub
      - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${publishArn}/invocations"
      - publishArn: !ImportValue FunctionLambdaForPublishArn
  DownloadReportIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref UtilitiesApi
      Description: Download reports lambda API GW Integration
      IntegrationType: AWS_PROXY
      PayloadFormatVersion: "2.0"
      IntegrationUri: !Sub
      - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${downloadArn}/invocations"
      - downloadArn: !ImportValue FunctionForDownloadArn
  # Production lambdas
  ProductionUpdaterIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref UtilitiesApi
      Description: Production Updater Lambda API GW Integration
      IntegrationType: AWS_PROXY
      PayloadFormatVersion: "2.0"
      IntegrationUri: !Sub
      - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${prodUpdaterArn}/invocations"
      - prodUpdaterArn: !ImportValue ProductionUpdaterArn
  ProductionFetcherIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref UtilitiesApi
      Description: Production Fetcher Lambda API GW Integration
      IntegrationType: AWS_PROXY
      PayloadFormatVersion: "2.0"
      IntegrationUri: !Sub
      - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${prodFetcherArn}/invocations"
      - prodFetcherArn: !ImportValue ProductionFetcherArn
  # Consumption Lambda
  ConsumptionFetcherIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref UtilitiesApi
      Description: Consumption Fetcher Lambda API GW Integration
      IntegrationType: AWS_PROXY
      PayloadFormatVersion: "2.0"
      IntegrationUri: !Sub
      - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${prodFetcherArn}/invocations"
      - prodFetcherArn: !ImportValue ConsumptionFetcherArn
  
  # ---- Routes ----
  # Report lambdas
  PublishLambdaApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref UtilitiesApi
      RouteKey: "PUT /api/report"
      Target: !Sub 
      - "integrations/${publishIntegrationId}"
      - publishIntegrationId: !GetAtt PublishLambdaIntegration.IntegrationId
      AuthorizationType: NONE
  DownloadLambdaApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref UtilitiesApi
      RouteKey: "GET /api/report{zone}/{date}"
      Target: !Sub 
      - "integrations/${downloadIntegrationId}"
      - downloadIntegrationId: !GetAtt DownloadReportIntegration.IntegrationId
      AuthorizationType: NONE
  # Production lambdas
  ProductionUpdaterLambdaApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref UtilitiesApi
      RouteKey: "POST /api/production"
      Target: !Sub 
      - "integrations/${prodUpdaterIntegrationId}"
      - prodUpdaterIntegrationId: !GetAtt ProductionUpdaterIntegration.IntegrationId
      AuthorizationType: NONE
  ProductionFetcherLambdaApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref UtilitiesApi
      RouteKey: "GET /api/production/{zone}/{date}"
      Target: !Sub 
      - "integrations/${prodFetcherIntegrationId}"
      - prodFetcherIntegrationId: !GetAtt ProductionFetcherIntegration.IntegrationId
      AuthorizationType: NONE
  # Consumption lambda
  ConsumptionFetcherLambdaApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref UtilitiesApi
      RouteKey: "GET /api/consumption/{zone}/{date}"
      Target: !Sub 
      - "integrations/${prodFetcherIntegrationId}"
      - prodFetcherIntegrationId: !GetAtt ConsumptionFetcherIntegration.IntegrationId
      AuthorizationType: NONE
  UtilitiesApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref UtilitiesApi
      StageName: !Ref PublishStageName
      AutoDeploy: true
Outputs:
  ApiGwUrl:
    Description: "Utilities API endpoint URL"
    Value: !Sub "https://${UtilitiesApi}.execute-api.${AWS::Region}.amazonaws.com/${PublishStageName}"
    Export:
      Name: ApiGwUrl