openapi: 3.0.3
info:
  title: Utilities API
  description: Documentación de la API para obtención de datos de consumo, producción y generación de reportes 
  version: 1.0.0
  contact:
    name: Immune API Support
    email: laura.bruges.cco@immune.institute
    url: https://github.com/lbruges/aws_capstone_project
servers:
  - url: "{{api_gw}}"
    description: API Gateway

paths:
  /api/production:
    post:
      summary: Crear o actualizar datos de producción
      operationId: updateProduction
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  example: "12-2024"
                  description: "Fecha en formato mes-año"
                zone:
                  type: string
                  example: "C"
                  description: "Identificador de zona"
                costPerM3:
                  type: number
                  format: float
                  example: 19
                  description: "Consumo por metro cúbico"
      responses:
        '200':
          description: Los datos de producción se han actualizado correctamente
        '400':
          description: El formato del payload es incorrecto o no se han incluído datos de la fecha, zona o producción
        '500':
          description: Error inesperado (por ejemplo, la tabla de producción no existe o no hay conexión con la base de datos)

  /api/production/{zone}/{date}:
    get:
      summary: Obtener costos de producción por zona y fecha
      operationId: getProductionCosts
      parameters:
        - in: path
          name: zone
          required: true
          schema:
            type: string
            example: "A"
            description: "Identificador de zona"
        - in: path
          name: date
          required: true
          schema:
            type: string
            example: "12-2024"
            description:  "Fecha en formato mes-año"
      responses:
        '200':
          description: Datos de costo de producción por metro cúbico por mes y zona
        '400':
          description: El formato de la ruta es incorrecto o no se han incluído datos de la fecha y/o zona
        '500':
          description: Error inesperado (por ejemplo, la tabla de producción no existe o no hay conexión con la base de datos)

  /api/consumption/{zone}/{date}:
    get:
      summary: Obtener datos de consumo promedio por zona y fecha
      operationId: getConsumption
      parameters:
        - in: path
          name: zone
          required: true
          schema:
            type: string
            example: "A"
            description: "Identificador de zona"
        - in: path
          name: date
          required: true
          schema:
            type: string
            example: "12-2024"
            description:  "Fecha en formato mes-año"
      responses:
        '200':
          description: Datos de consumo por zona por mes
        '400':
          description: No se han proveído datos de zona o fecha
        '500':
          description: Error inesperado (por ejemplo, la tabla de consumos no existe o no hay conexión con la base de datos)


  /api/report:
    put:
      summary: Generar uno o múltiples reportes y actualizar la base de datos de utilidades
      operationId: generateReport
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                SQSEvent:
                  type: array
                  items:
                    type: object
                    properties:
                      zone:
                        type: string
                        example: "B"
                        description: "Identificador de zona"
                      date:
                        type: string
                        example: "12-2024"
                        description:  "Fecha en formato mes-año"
      responses:
        '200':
          description: Se ha encolado una solicitud de generación de reporte(s)
        '500':
          description: Ha ocurrido un error inesperado

  /api/report/{zone}/{date}:
    get:
      summary: Descargar reportes
      operationId: downloadReport
      parameters:
        - in: path
          name: zone
          required: true
          schema:
            type: string
            example: "A"
            description: "Identificador de zona"
        - in: path
          name: date
          required: true
          schema:
            type: string
            example: "12-2024"
            description:  "Fecha en formato mes-año"
      responses:
        '200':
          description: Reporte generado en pdf correspondiente a las utilidades para el mes y zona proveídos
        '400':
          description: La fecha o zona no han sido proveídos
