version: '3.9'
services:
  localstack: # LocalStack container
    image: localstack/localstack:latest
    ports:
      # Map the port so you can access the API from the host machine
      - 4566:4566
    hostname: custom-localstack
    networks:
      - default
    #volumes:
      # Here you mount your setup file so it will be executed
      # when the container starts
      #- ./localstack-setup.sh:/etc/localstack/init/ready.d/script.sh